name: 'WordPress Plugin Build Zip'
description: 'Build a release zip of a WordPress Plugin'
author: '10up'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  retention-days:
    description: 'How many days to keep the zip archive'
    default: 5
  artifact-name:
    description: 'Name of the uploaded artifact'
    default: ${{ github.event.repository.name }}
  upload-plugin-artifact:
    description: 'Whether to upload the plugin artifact'
    default: true
    type: boolean
runs:
  using: 'composite'
  steps:
    - name: Generate zip archive
      id: archive
      run: ${{ github.action_path }}/build-zip.sh
      shell: bash

    - name: Unzip the archive (prevents double zip problem)
      id: unzip
      run: |
        mkdir -p zipfile/${{ env.SLUG }}
        unzip ${{ github.event.repository.name }}.zip -d zipfile/${{ env.SLUG }}
      shell: bash

    - name: Upload the archive as an artifact
      id: upload-plugin-artifact
      if: ${{ inputs.upload-plugin-artifact == 'true' }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: ${{ inputs.artifact-name }}
        path: zipfile
        retention-days: ${{ inputs.retention-days }}
outputs:
  zipfile-path:
    description: 'Path to the zipfile directory'
    value: zipfile
  artifact-id:
    description: 'ID of the uploaded artifact'
    value: ${{ steps.upload-plugin-artifact.outputs.artifact-id }}
  artifact-url:
    description: 'URL of the uploaded artifact'
    value: ${{ steps.upload-plugin-artifact.outputs.artifact-url }}
